In [13]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # self.linear = nn.Linear(num_features, 1)
    # self.sigmoid = nn.Sigmoid()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    # output = self.linear(features) # for e.g, z = wx + b
    # output = self.sigmoid(output) # sigmoid(z)
    output = self.network(features)

    return output


In [23]:
# create dataset
features = torch.rand(5,3)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3306],
        [0.3292],
        [0.3146],
        [0.3091],
        [0.3264]], grad_fn=<SigmoidBackward0>)

In [27]:
# show model layer weights
model.network[0].weight

Parameter containing:
tensor([[ 0.2178,  0.4607, -0.4661],
        [-0.3931,  0.4315, -0.0321],
        [ 0.5272, -0.0331,  0.1769]], requires_grad=True)

In [31]:
# show model bias
model.network[0].bias

Parameter containing:
tensor([-0.2600,  0.2909,  0.4009], requires_grad=True)

In [10]:
!pip install torchinfo

In [32]:
from torchinfo import summary
summary(model, input_size=(5,3))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [5, 1]                    --
├─Sequential: 1-1                        [5, 1]                    --
│    └─Linear: 2-1                       [5, 3]                    12
│    └─ReLU: 2-2                         [5, 3]                    --
│    └─Linear: 2-3                       [5, 1]                    4
│    └─Sigmoid: 2-4                      [5, 1]                    --
Total params: 16
Trainable params: 16
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00