<a href="https://colab.research.google.com/github/divyansshu/pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


# pytorch tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([1, 2])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1,2,3], [3,4,5], [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

# Random Tensors

In [ ]:
# random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8020, 0.3805, 0.1199, 0.4959],
        [0.5313, 0.3914, 0.4115, 0.1782],
        [0.0221, 0.3006, 0.0431, 0.2316]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor

tensor([[[0.8465, 0.6177, 0.5180],
         [0.1167, 0.1580, 0.5505],
         [0.1705, 0.4001, 0.8454],
         ...,
         [0.1309, 0.2026, 0.9125],
         [0.8862, 0.5796, 0.2135],
         [0.7210, 0.2361, 0.4412]],

        [[0.1684, 0.0373, 0.2176],
         [0.9626, 0.3125, 0.3594],
         [0.8424, 0.2377, 0.3043],
         ...,
         [0.1874, 0.5586, 0.9454],
         [0.4583, 0.1446, 0.7865],
         [0.2412, 0.7243, 0.8194]],

        [[0.1816, 0.6181, 0.8377],
         [0.4060, 0.3916, 0.4010],
         [0.5260, 0.5387, 0.2899],
         ...,
         [0.8747, 0.5532, 0.7959],
         [0.4657, 0.2843, 0.4367],
         [0.5604, 0.2485, 0.6503]],

        ...,

        [[0.0992, 0.4834, 0.3439],
         [0.6946, 0.5615, 0.9491],
         [0.8364, 0.2888, 0.3942],
         ...,
         [0.0247, 0.4897, 0.0326],
         [0.7180, 0.7555, 0.9023],
         [0.0144, 0.9325, 0.5435]],

        [[0.5554, 0.6321, 0.3404],
         [0.2573, 0.1974, 0.7332],
         [0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

# zeroes and ones

In [ ]:
# create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# create a range of tensors and tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.range(start=1, end=100, step = 5)

/tmp/ipykernel_5246/3495591777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=1, end=100, step = 5)


tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46., 51., 56., 61., 66.,
        71., 76., 81., 86., 91., 96.])

In [ ]:
# creating tensors like
zero_mat = torch.zeros_like(input=TENSOR)
zero_mat

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

# Tensor Datatypes

# Tensors datatype is one of the 3 big errors in pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_64_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

# Manipulating tensors

In [ ]:
t = torch.tensor([1,2,3])
print(t+10)
print(10 - t)
print(10*t)
print(t//10)
print(t%10)

tensor([11, 12, 13])
tensor([9, 8, 7])
tensor([10, 20, 30])
tensor([0, 0, 0])
tensor([1, 2, 3])


In [ ]:
t1 = torch.tensor([4,8])
t2 = torch.tensor([2,4])
print(t1+t2)
print(t1-t2)
print(t1//t2)
print(t1%t2)

tensor([ 6, 12])
tensor([2, 4])
tensor([2, 2])
tensor([0, 0])


In [ ]:
# pytorch in-built functions
torch.mul(t,10)

tensor([10, 20, 30])

In [ ]:
torch.add(t,2)

tensor([3, 4, 5])

In [ ]:
torch.sub(t,5)

tensor([-4, -3, -2])

In [ ]:
torch.div(t,10)

tensor([0.1000, 0.2000, 0.3000])

#matrix multiplication

In [ ]:
# element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*" , tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

# matrix transpose

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [4,5]])
tensor_B = torch.tensor([[1,2],[2,3],[4,5]])

torch.matmul(tensor_A , tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B

tensor([[1, 2],
        [2, 3],
        [4, 5]])

In [ ]:
tensor_B.T

tensor([[1, 2, 4],
        [2, 3, 5]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 5,  8, 14],
        [ 8, 13, 23],
        [14, 23, 41]])

# finding the min, max, mean, sum,etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

# find the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [ ]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

#Reshaping, stacking, squeezing, unsqueezing tensors

In [ ]:
# change the shape
x = torch.arange(1.,7.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6.]), torch.Size([6]))

In [ ]:
reshaped = x.reshape(2,3)
reshaped,reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]))

In [ ]:
# change the view
z = x.view(2,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]))

In [ ]:
# changing z changes x because a view of a tensor shares the same memory as the original tensor
z[: ,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.]]),
 tensor([5., 2., 3., 5., 5., 6.]))

In [ ]:
# stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]])

In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x = torch.tensor([[1,2,3,4,5,6,7,8,9]], dtype=torch.float32)
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x.shape

torch.Size([1, 9])

In [ ]:
x.squeeze_()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x.ndim

1

The `squeeze()` method returns a tensor with all the dimensions of input of size `1` removed. However, it does not modify the tensor in-place. To modify the tensor in-place, you need to use `squeeze_()`.

In [ ]:
y = torch.tensor([[1,2,3,4,5,6,7,8,9]], dtype=torch.float32)
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(f'Previous tensor: {y}')
print(f'Previous tensor shape: {y.shape}')
print(f'Previous tensor dim: {y.ndim}')
y_ = y.squeeze()
print(f'New tensor: {y_}')
print(f'New tensor shape: {y_.shape}')
print(f'New tensor dim: {y_.ndim}')

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor shape: torch.Size([1, 9])
Previous tensor dim: 2
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape: torch.Size([9])
New tensor dim: 1


In [ ]:
z = torch.tensor([1,2,3,4,5,6,7,8,9], dtype=torch.float32)
z

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() - adds a single dimenstion to a target tensor at a specific dimension
print(f'Previous tensor: {z}')
print(f'Previous tensor shape: {z.shape}')
print(f'Previous tensor dim: {z.ndim}')
z_ = z.unsqueeze(dim=1)
print(f'New tensor: {z_}')
print(f'New tensor shape: {z_.shape}')
print(f'New tensor dim: {z_.ndim}')

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous tensor shape: torch.Size([9])
Previous tensor dim: 1
New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New tensor shape: torch.Size([9, 1])
New tensor dim: 2


In [ ]:
# torch.permute: rearrange the dimensions of a target tensor in a specified order
a = torch.rand(size=(224,224,3))

a_permute = a.permute(2,0,1)

print(f'Previous shape: {a.shape}')
print(f'New shape: {a_permute.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
a[0,0,0] = 3456

In [ ]:
a[0,0,0], a_permute[0,0,0]

(tensor(3456.), tensor(3456.))

# Indexing
indexing with pytorch is similar to indexing with numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0,0,0], x[0,0], x[0]

(tensor(1),
 tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

# Numpy array to pytorch tensors

In [ ]:
import torch
import numpy as np
array = np.arange(1.0,9.0)
array

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
# numpy array to tensor
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
tensor_to_numpy = tensor.numpy()
tensor_to_numpy

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
tensor.dtype

torch.float32

# Reproducibility

In [ ]:
# create two random tensors
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print(tensor_A)
print(tensor_B)

tensor([[0.5670, 0.0678, 0.2339, 0.4024],
        [0.9716, 0.6093, 0.7759, 0.6606],
        [0.8037, 0.6305, 0.8320, 0.9614]])
tensor([[0.2440, 0.0903, 0.0877, 0.5827],
        [0.5664, 0.6083, 0.8982, 0.0880],
        [0.5178, 0.6699, 0.1105, 0.1676]])


In [ ]:
tensor_A == tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(3,4)

print(tensor_c)
print(tensor_d)
print(tensor_c == tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
