In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [3]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'using GPU: {torch.cuda.get_device_name(0)}')
else:
  print('GPU not available using CPU')

GPU not available using CPU


# Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)
# allocates space in memory of (2,3) shape
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeroes
torch.zeros(2,3)
# creates an array of (2,3) shape with value zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)
# creates an array of shape (2,3) of value 1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)
# creates an array of shape(2,3) with random values between 0 and 1

tensor([[0.0542, 0.4359, 0.5142],
        [0.3617, 0.1957, 0.6008]])

In [9]:
# rand creates arrays with different values at each different call
torch.rand(2,3)


tensor([[0.1186, 0.4184, 0.0967],
        [0.4214, 0.8267, 0.0850]])

In [10]:
# use of seed
# seed does not let change the values of arrays using rand at each different call, multiple users can now access same array values using rand keyword, but seed value must be same

torch.manual_seed(100)
print(torch.rand(2,3))

torch.manual_seed(100)
print(torch.rand(2,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [11]:
# using tensor
torch.tensor([[1,2,3], [4,5,6]])
# using tensor we can create any kind of array 1d,2d,Nd..

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# arange
print('using range ->', torch.range(0,10,2))

using range -> tensor([ 0.,  2.,  4.,  6.,  8., 10.])


/tmp/ipykernel_9720/3503695580.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print('using range ->', torch.range(0,10,2))


In [13]:
# using linspace
print('using linspace ->', torch.linspace(10,20,10))
# linspace is linearly space, it creates evenly spaced 1d array

using linspace -> tensor([10.0000, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778,
        18.8889, 20.0000])


In [14]:
# using eye
print('using eye ->', torch.eye(3))
# eye is identity matrix, it creates an identity matrix of given size

using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
# using full
print('using full ->', torch.full((3,3),5))
# full creates a matrix of 3 x 3 of number 5

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes


In [16]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[1150452160, 1075969088,          0],
        [         0,          0,          0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# susing to()
x.to(torch.float32)
# to() can change data type of any tensor to another type

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## 1. Scalar operation

In [31]:
x = torch.tensor([[1,2,3],[1,2,3]])
x

tensor([[1, 2, 3],
        [1, 2, 3]])

In [32]:
# addition
x + 2

tensor([[3, 4, 5],
        [3, 4, 5]])

In [33]:
# subtraction
x - 2

tensor([[-1,  0,  1],
        [-1,  0,  1]])

In [34]:
# multiplication
x * 2

tensor([[2, 4, 6],
        [2, 4, 6]])

In [35]:
# division
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [0.5000, 1.0000, 1.5000]])

In [36]:
# int division
x // 2

tensor([[0, 1, 1],
        [0, 1, 1]])

In [37]:
# mod
x % 2

tensor([[1, 0, 1],
        [1, 0, 1]])

In [38]:
# power
x**2

tensor([[1, 4, 9],
        [1, 4, 9]])

## 2. Element wise operation

In [39]:
a = torch.tensor([[2,4,6], [2,4,6]])
b = torch.tensor([[1,2,3],[1,2,3]])
print(a)
print(b)

tensor([[2, 4, 6],
        [2, 4, 6]])
tensor([[1, 2, 3],
        [1, 2, 3]])


In [40]:
# addition
a + b

tensor([[3, 6, 9],
        [3, 6, 9]])

In [42]:
# subtraction
a - b

tensor([[1, 2, 3],
        [1, 2, 3]])

In [43]:
# multiply
a * b

tensor([[ 2,  8, 18],
        [ 2,  8, 18]])

In [45]:
# division
a / b

tensor([[2, 2, 2],
        [2, 2, 2]])

In [46]:
# power
a ** b

tensor([[  2,  16, 216],
        [  2,  16, 216]])

In [47]:
# mod
a % b

tensor([[0, 0, 0],
        [0, 0, 0]])

In [49]:
z = torch.tensor([-1,-2,3,4])
z

tensor([-1, -2,  3,  4])

In [50]:
torch.abs(z)

tensor([1, 2, 3, 4])

In [51]:
torch.neg(z)

tensor([ 1,  2, -3, -4])

In [52]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [53]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [54]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [55]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [57]:
# clamp
torch.clamp(d, min=2, max=3) # clamp can be used to set range

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction operation

In [65]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [66]:
# sum
torch.sum(e) # calculate sum of all elements of tensor

tensor(29.)

In [67]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 5., 15.,  9.])

In [68]:
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [69]:
# mean
torch.mean(e)

tensor(4.8333)

In [70]:
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [71]:
# mean along rows
torch.mean(e, dim=1)

tensor([3.3333, 6.3333])

In [72]:
# median
torch.median(e)

tensor(4.)

In [73]:
# max
torch.max(e)

tensor(9.)

In [75]:
# min
torch.min(e)

tensor(0.)

In [78]:
# product
torch.prod(e)

tensor(0.)

In [79]:
# std
torch.std(e)

tensor(3.8687)

In [80]:
# variance
torch.var(e)

tensor(14.9667)

In [81]:
# argmax
torch.argmax(e) # returns the index of max element in tensor

tensor(4)

In [82]:
# argmin
torch.argmin(e) # returns the index of min element in tensor

tensor(2)